# This workflow will install Python dependencies and run tests with a single version of Python

name: Unit Tests

on:
  push:
    branches: [ master ]

jobs:
  run-unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pytest
    - name: Test with pytest
      run: |
        pytest
